$Id: BUILD,v 1.3 2001/07/20 00:01:22 bhudson Exp $

Type:
        ./configure

The only thing likely to fail is that you don't have the scripting language
perl installed.  If this is the case, go to www.perl.com and download this
extremely useful program (or get it off your linux distribution's web
page).  You need to have version 5 or later.
